### ISSUE TITLE
CI: to-do list

### ISSUE THREAD

**Issue by noc0lour** [gnuradio/gnuradio#1271]
Expand test matrix:

## per PR
- [x] next: ubuntu 16.04 qt5 
- [x] python3: ubuntu 16.04 py2
- [ ] codecov.io
- [ ] cppcheck delta
- [ ] abichecker delta

## on push:
- [x] all PR tests (minus mergeability)
- [ ] Include-what-you-use report
- [ ] documentation generation

## weekly:
- [ ] all PR tests (minus mergeability)
- [ ] coverity (on master)

In general: 
- [x] specify DESIRED_QT_VERSION
- [x] specify PYTHON_EXECUTABLE
- [x] install QT5 
- [x] install python mako
- [x] fix SSL cert
- [ ] display 200 changes by default in console view
- [x] disable qa_zeromq_sub

**Comment by jmcorgan** [comment]
For Ubuntu 16.04, next branch, QT4, you need to specify -DDESIRED_QT_VERSION=4, and use an builder image with QT4 installed.

For Ubuntu 16.04, next branch, QT5, you need to use an builder image with QT5 installed.

**Comment by jmcorgan** [comment]
We need to have the deps installed for building the docs and turn that on in all the builders.

**Comment by kartikp1995** [comment]
Not sure if this is the right place but add "setting up SSL certificate for `ci.gnuradio.org`" in checklist. :)

**Comment by noc0lour** [comment]
@kartikp1995 look at this shiny SSL everywhere (:

**Comment by noc0lour** [comment]
Move CI todo list to the CI repo: https://github.com/gnuradio/gnuradio-buildbot/issues
