### ISSUE TITLE
Apply a bit of clang-tidy

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#2720]
# Purpose

This is a running list so that we (I) don't do things thrice.

Extend at your own will, if you think a specific operation is useful

## simple

things that most likely just change a couple of characters in singular lines and are simply kind of obvious

- [x] modernize-use-nullptr
- [ ] modernize-use-bool-literals
- [x] readability-simplify-boolean-expr + misc-redundant-expression
- [ ] boost-use-to-string (maybe do manually)
- [ ] readability-braces-around-statements
- [x] misc-static-assert
- [x] misc-throw-by-value-catch-by-reference (fixes #2704)
- [x] readability-container-size-empty (empty() instead of size() == 0 and similar)
- [x] readability-redundant-declaration

## complex

- [ ] `performance-*` (#2725)
- [ ] modernize-use-emplace #2820 
- [ ] modernzie-loop-convert #2820 
- [ ] modernize-use-auto (run together with loop-convert) #2820 
- [ ] modernize-use-override (especially interesting in our humongous codebase of `general_work`s)
- [ ] modernize-make-shared (simplifies almost all `::make`)
- [ ] modernize-shrink-to-fit
- [ ] modernize-use-default-member-init + modernize-use-equals-default
- [ ] readability-convert-member-functions-to-static + readability-static-accessed-through-instance
- [ ] readability-static-accessed-through-instance

## code quality checks

probably not auto-fixable

- [ ] hicpp-signed-bitwise
- [x] modernize-deprecated-headers
